# Generated by Django 5.2.4 on 2025-08-04 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='phone_number',
            field=models.CharField(help_text='9123456789', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be 10 digits long and without leading zeros')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('reader', 'Reader')], default='admin', max_length=10),
        ),
    ]
