# Generated by Django 5.2.4 on 2025-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_authorprofile_user_alter_readerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_categories_blogs', to='blog.subcategory'),
        ),
    ]
