# Generated by Django 5.2.4 on 2025-08-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_sub_category_blog_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sub_category',
            new_name='sub_categories',
        ),
    ]
