# Generated by Django 5.2.4 on 2025-08-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_sub_category_blog_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent_comments', to='blog.comment'),
        ),
    ]
